import React from 'react'
import type { Metadata } from 'next'
import { Shield, Lock, Eye, Database, Globe, Mail } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Lumina privacy policy — a 100% offline app that collects zero data.',
}

const sections = [
  {
    icon: Lock,
    title: 'Data Collection',
    content: `Lumina collects absolutely no personal data. The application runs entirely on your local machine and does not make any outbound network requests to our servers, analytics platforms, or third-party services.

There are no user accounts, no registration, no email capture, and no telemetry of any kind.`,
  },
  {
    icon: Database,
    title: 'Local Storage Only',
    content: `All data generated by Lumina — including your prompt history, custom templates, settings, and context documents — is stored exclusively in a local SQLite database on your computer.

This database is located in your operating system's app data directory. You have full ownership and control of this data. You can inspect, backup, or delete it at any time.`,
  },
  {
    icon: Globe,
    title: 'Network Requests',
    content: `Lumina makes network requests only to your local Ollama server (http://localhost:11434). This is purely local — it never leaves your machine.

The only time Lumina requires internet access is when you intentionally pull a new AI model through Ollama (e.g. ollama pull qwen3:8b). This is a one-time download directly from Ollama's servers — Lumina has no involvement in or visibility into this request.`,
  },
  {
    icon: Eye,
    title: 'What We Can\'t See',
    content: `Because Lumina is a locally-installed desktop application, we have no technical ability to see:

• What text you process with Lumina
• Which prompts or templates you use
• What AI models you run
• How often you use the application
• Your operating system, hardware, or IP address

This is by design. Privacy is not a feature we bolted on — it is the fundamental architecture of Lumina.`,
  },
  {
    icon: Shield,
    title: 'Open Source Guarantee',
    content: `Lumina is fully open source. Every line of code is publicly available on GitHub at github.com/rachanadn27-boop/lumina-ai.

You can audit exactly what the application does, how it communicates with Ollama, what it writes to disk, and confirm for yourself that no data leaves your machine. We welcome security researchers and privacy auditors to review our codebase.`,
  },
  {
    icon: Mail,
    title: 'Contact',
    content: `If you have any privacy-related questions or want to report a security concern, please open an issue on our GitHub repository.

We treat security reports with urgency and will respond as quickly as possible.`,
  },
]

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-bg-dark">
      {/* Header */}
      <div className="relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[500px] h-[200px] bg-green-500/5 rounded-full blur-[100px] pointer-events-none" />
        <div className="max-w-3xl mx-auto px-4 pt-20 pb-10 relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-green-500/10 border border-green-500/20 text-xs text-green-300 font-bold mb-6">
            <Shield className="w-3.5 h-3.5" />
            Zero Data Collection — By Design
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-white font-outfit mb-4">Privacy Policy</h1>
          <p className="text-sm text-gray-400 leading-relaxed">
            Lumina is a 100% offline desktop application. This privacy policy is short because there is almost nothing to say: <strong className="text-white">we collect no data whatsoever.</strong>
          </p>
          <p className="text-xs text-gray-600 mt-3">Last updated: June 2026</p>
        </div>
      </div>

      {/* TL;DR Banner */}
      <div className="max-w-3xl mx-auto px-4 mb-8">
        <div className="p-5 rounded-2xl bg-green-500/5 border border-green-500/15 flex items-start gap-4">
          <div className="w-8 h-8 rounded-xl bg-green-500/10 border border-green-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
            <Shield className="w-4 h-4 text-green-400" />
          </div>
          <div>
            <p className="text-sm font-bold text-white mb-1">TL;DR</p>
            <p className="text-xs text-gray-400 leading-relaxed">
              Lumina runs 100% on your device. We have no servers, no analytics, no accounts, and no telemetry. Your text, prompts, and history never leave your computer. Ever.
            </p>
          </div>
        </div>
      </div>

      {/* Sections */}
      <div className="max-w-3xl mx-auto px-4 pb-20 space-y-4">
        {sections.map(({ icon: Icon, title, content }, i) => (
          <div key={title} className="p-6 rounded-2xl bg-bg-darkSecondary border border-white/5 space-y-3">
            <h2 className="text-base font-bold text-white flex items-center gap-2.5">
              <span className="w-7 h-7 rounded-lg bg-brand-primary/10 border border-brand-primary/20 flex items-center justify-center flex-shrink-0">
                <Icon className="w-3.5 h-3.5 text-brand-primary" />
              </span>
              {i + 1}. {title}
            </h2>
            <div className="text-xs text-gray-400 leading-relaxed whitespace-pre-line pl-10">
              {content}
            </div>
          </div>
        ))}

        {/* Footer note */}
        <div className="text-center pt-4">
          <p className="text-xs text-gray-600">
            Questions?{' '}
            <a
              href="https://github.com/rachanadn27-boop/lumina-ai/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:text-white transition underline"
            >
              Open a GitHub issue
            </a>
          </p>
        </div>
      </div>
    </div>
  )
}
